name: Pytest testing

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: 'true'
          repository: Cislunar-Explorers/FlightSoftware
          path: './src/fsw'
          ref: a514cd98dea499f126a7d72ca970710a01ab3b98
      - name: Pull & update submodules recursively
        run: |
          git submodule update --init --recursive
          git submodule update --recursive --remote
          git pull --recurse-submodules
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
      - name: Make .env
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_CISLUNAR_BASE_DIR: "cislunar_data"
          envkey_FOR_FLIGHT: "0"
          envkey_LOG: "1"
          file_name: .env
      - name: Test with pytest
        run: |
          pytest
      - name: Run pyright
        uses: jakebailey/pyright-action@v1.0.2