name: Pytest testing

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
      - name: Pull & update submodules recursively
        run: |
          git submodule update --init --recursive
          git submodule update --recursive --remote
          git pull --recurse-submodules
      - name: Test with pytest
        run: |
          pytest
      - name: Run pyright
        uses: jakebailey/pyright-action@v1.0.2